import type { McpClientResult, Tool, ToolParam } from "./client.js";

export interface OAuthTokenInfo {
  access_token: string;
  refresh_token: string;
  expires_in: number | null;
  token_endpoint: string;
  client_id: string;
  client_secret?: string;
  mcp_oauth: boolean;
  token_encoding: "basic" | "none";
  resource_url: string | null;
  provider: string;
  mcp_url: string;
  tokenFilePath?: string;
}

function slugify(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}

function buildExampleArgs(params: ToolParam[]): string {
  const required = params.filter((p) => p.required);
  if (required.length === 0) return "'{}'";

  const example: Record<string, string> = {};
  for (const p of required) {
    example[p.name] = `<${p.name}>`;
  }
  return `'${JSON.stringify(example)}'`;
}

function generateSkillMd(result: McpClientResult, skillName: string): string {
  const { serverInfo, tools, serverUrl } = result;

  const triggerPhrases = tools
    .map((t) => t.name.replace(/-/g, " "))
    .join(", ");

  const toolDocs = tools
    .map((t) => {
      const paramLines = t.params.map((p) => {
        const req = p.required ? " (required)" : " (optional)";
        const desc = p.description ? `: ${p.description}` : "";
        return `  - \`${p.name}\` (${p.type})${req}${desc}`;
      });

      const exampleArgs = buildExampleArgs(t.params);

      return [
        `### ${t.name}`,
        "",
        t.description,
        "",
        ...(paramLines.length > 0 ? ["**Parameters:**", ...paramLines, ""] : []),
        "```bash",
        `$HOME/.openclaw/skills/${skillName}/scripts/${skillName}.sh ${t.name} ${exampleArgs}`,
        "```",
      ].join("\n");
    })
    .join("\n\n");

  // requires.bins: [] — don't require curl; gateway's PATH at load time is often
  // minimal (systemd/Docker), so bin checks fail. Script runs in agent context.
  // always: true — bypass eligibility checks so skill reliably appears in list.
  const metadataJson = JSON.stringify({
    clawdbot: {},
    openclaw: { requires: { bins: [] }, always: true },
  });

  const desc = `${serverInfo.instructions ?? `Use ${serverInfo.name} tools.`} Triggers on: ${triggerPhrases}.`;
  const escapedDesc = desc
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\n/g, "\\n")
    .replace(/\r/g, "\\r");

  return [
    "---",
    `name: ${skillName}`,
    `description: "${escapedDesc}"`,
    `homepage: ${serverUrl}`,
    `allowed-tools: Bash(curl:*)`,
    `metadata: ${metadataJson}`,
    "---",
    "",
    `# ${serverInfo.name}`,
    "",
    serverInfo.instructions ?? "",
    "",
    "## Quick Start",
    "",
    "```bash",
    `$HOME/.openclaw/skills/${skillName}/scripts/${skillName}.sh <tool-name> '<json-args>'`,
    "```",
    "",
    "## Tools",
    "",
    toolDocs,
  ]
    .join("\n")
    .trim() + "\n";
}

function curlHeaderLines(extraHeaders: Record<string, string>): string[] {
  return Object.entries(extraHeaders).map(([k, v]) => `  -H "${k}: ${v}" \\`);
}

function generateStaticShellScript(result: McpClientResult, skillName: string): string {
  const { serverUrl, extraHeaders } = result;
  const headerLines = curlHeaderLines(extraHeaders);

  const initBody = JSON.stringify({
    jsonrpc: "2.0",
    id: 0,
    method: "initialize",
    params: {
      protocolVersion: "2024-11-05",
      capabilities: {},
      clientInfo: { name: "mcptoskill", version: "0.1.0" },
    },
  });

  const lines = [
    "#!/bin/bash",
    `# Generated by mcptoskill — https://mcptoskill.com`,
    `# Server: ${result.serverInfo.name} v${result.serverInfo.version}`,
    `# URL: ${serverUrl}`,
    "set -euo pipefail",
    "",
    `TOOL_NAME="\${1:?Usage: ${skillName}.sh <tool-name> '<json-args>'}"`,
    `ARGS="\${2:-}"`,
    `[ -z "$ARGS" ] && ARGS='{}'`,
    `MCP_URL="${serverUrl}"`,
    "",
    "# Capture session ID from initialize (required for stateful servers; no-op for stateless)",
    "TEMP_HEADERS=$(mktemp)",
    "curl -s -X POST \"$MCP_URL\" \\",
    "  -H \"Content-Type: application/json\" \\",
    "  -H \"Accept: application/json, text/event-stream\" \\",
    ...headerLines,
    "  -D \"$TEMP_HEADERS\" \\",
    `  -d '${initBody}' > /dev/null`,
    "",
    "SESSION_ID=$(grep -i \"^mcp-session-id:\" \"$TEMP_HEADERS\" | awk '{print $2}' | tr -d '\\r' || true)",
    "rm -f \"$TEMP_HEADERS\"",
    "",
    "# Call the tool",
    "if [ -n \"$SESSION_ID\" ]; then",
    "  RESPONSE=$(curl -s -X POST \"$MCP_URL\" \\",
    "    -H \"Content-Type: application/json\" \\",
    "    -H \"Accept: application/json, text/event-stream\" \\",
    ...headerLines.map((l) => l.replace(/^  /, "    ")),
    "    -H \"Mcp-Session-Id: $SESSION_ID\" \\",
    `    -d "{\\"jsonrpc\\":\\"2.0\\",\\"id\\":1,\\"method\\":\\"tools/call\\",\\"params\\":{\\"name\\":\\"$TOOL_NAME\\",\\"arguments\\":$ARGS}}")`,
    "else",
    "  RESPONSE=$(curl -s -X POST \"$MCP_URL\" \\",
    "    -H \"Content-Type: application/json\" \\",
    "    -H \"Accept: application/json, text/event-stream\" \\",
    ...headerLines.map((l) => l.replace(/^  /, "    ")),
    `    -d "{\\"jsonrpc\\":\\"2.0\\",\\"id\\":1,\\"method\\":\\"tools/call\\",\\"params\\":{\\"name\\":\\"$TOOL_NAME\\",\\"arguments\\":$ARGS}}")`,
    "fi",
    "",
    "# Handle SSE format (event: message / data: {...}) or plain JSON",
    "if echo \"$RESPONSE\" | grep -q '^data: '; then",
    "  echo \"$RESPONSE\" | grep '^data: ' | tail -1 | sed 's/^data: //'",
    "else",
    "  echo \"$RESPONSE\"",
    "fi",
    "",
  ];

  return lines.join("\n");
}

function generateOAuthShellScript(
  result: McpClientResult,
  skillName: string,
  oauth: OAuthTokenInfo,
): string {
  const { serverUrl } = result;

  const tokenFilePath = oauth.tokenFilePath
    ?? `$HOME/.openclaw/mcptoskill/tokens/${skillName}.json`;

  const initBody = JSON.stringify({
    jsonrpc: "2.0",
    id: 0,
    method: "initialize",
    params: {
      protocolVersion: "2024-11-05",
      capabilities: {},
      clientInfo: { name: "mcptoskill", version: "0.1.0" },
    },
  });

  // Supabase requires Basic auth for refresh even with dynamic registration; check first
  const refreshFunction =
    oauth.provider === "supabase" && oauth.client_secret
      ? generateSupabaseRefreshFunction(oauth)
      : oauth.mcp_oauth
        ? generateClientSideRefreshFunction(oauth)
        : generateProxiedRefreshFunction(oauth);

  const lines = [
    "#!/bin/bash",
    `# Generated by mcptoskill — https://mcptoskill.com`,
    `# Server: ${result.serverInfo.name} v${result.serverInfo.version}`,
    `# URL: ${serverUrl}`,
    `# OAuth: ${oauth.provider} (auto-refresh enabled)`,
    "set -euo pipefail",
    "",
    `TOOL_NAME="\${1:?Usage: ${skillName}.sh <tool-name> '<json-args>'}"`,
    `ARGS="\${2:-}"`,
    `[ -z "$ARGS" ] && ARGS='{}'`,
    `MCP_URL="${serverUrl}"`,
    `TOKEN_FILE="${tokenFilePath}"`,
    "",
    "# --- Token management ---",
    "",
    "read_token() {",
    "  if [ ! -f \"$TOKEN_FILE\" ]; then",
    `    echo "Error: token file not found at $TOKEN_FILE" >&2`,
    `    echo "Re-run: npx @filiksyos/mcptoskill ${serverUrl}" >&2`,
    "    exit 1",
    "  fi",
    "  ACCESS_TOKEN=$(jq -r '.access_token' \"$TOKEN_FILE\")",
    "}",
    "",
    "is_expired() {",
    "  local expires_at",
    "  expires_at=$(jq -r '.expires_at // 0' \"$TOKEN_FILE\")",
    "  if [ \"$expires_at\" = \"null\" ] || [ \"$expires_at\" = \"0\" ]; then",
    "    return 1",
    "  fi",
    "  local now",
    "  now=$(date +%s)",
    "  [ \"$now\" -ge \"$((expires_at - 60))\" ]",
    "}",
    "",
    ...refreshFunction,
    "",
    "ensure_fresh_token() {",
    "  read_token",
    "  if is_expired; then",
    "    refresh_token_flow",
    "    read_token",
    "  fi",
    "}",
    "",
    "ensure_fresh_token",
    "",
    "# --- MCP call ---",
    "",
    "AUTH_HEADER=\"Authorization: Bearer $ACCESS_TOKEN\"",
    "",
    "TEMP_HEADERS=$(mktemp)",
    "curl -s -X POST \"$MCP_URL\" \\",
    "  -H \"Content-Type: application/json\" \\",
    "  -H \"Accept: application/json, text/event-stream\" \\",
    "  -H \"$AUTH_HEADER\" \\",
    "  -D \"$TEMP_HEADERS\" \\",
    `  -d '${initBody}' > /dev/null`,
    "",
    "SESSION_ID=$(grep -i \"^mcp-session-id:\" \"$TEMP_HEADERS\" | awk '{print $2}' | tr -d '\\r' || true)",
    "rm -f \"$TEMP_HEADERS\"",
    "",
    "if [ -n \"$SESSION_ID\" ]; then",
    "  RESPONSE=$(curl -s -X POST \"$MCP_URL\" \\",
    "    -H \"Content-Type: application/json\" \\",
    "    -H \"Accept: application/json, text/event-stream\" \\",
    "    -H \"$AUTH_HEADER\" \\",
    "    -H \"Mcp-Session-Id: $SESSION_ID\" \\",
    `    -d "{\\"jsonrpc\\":\\"2.0\\",\\"id\\":1,\\"method\\":\\"tools/call\\",\\"params\\":{\\"name\\":\\"$TOOL_NAME\\",\\"arguments\\":$ARGS}}")`,
    "else",
    "  RESPONSE=$(curl -s -X POST \"$MCP_URL\" \\",
    "    -H \"Content-Type: application/json\" \\",
    "    -H \"Accept: application/json, text/event-stream\" \\",
    "    -H \"$AUTH_HEADER\" \\",
    `    -d "{\\"jsonrpc\\":\\"2.0\\",\\"id\\":1,\\"method\\":\\"tools/call\\",\\"params\\":{\\"name\\":\\"$TOOL_NAME\\",\\"arguments\\":$ARGS}}")`,
    "fi",
    "",
    "# Handle SSE format (event: message / data: {...}) or plain JSON",
    "if echo \"$RESPONSE\" | grep -q '^data: '; then",
    "  echo \"$RESPONSE\" | grep '^data: ' | tail -1 | sed 's/^data: //'",
    "else",
    "  echo \"$RESPONSE\"",
    "fi",
    "",
  ];

  return lines.join("\n");
}

function generateClientSideRefreshFunction(oauth: OAuthTokenInfo): string[] {
  const resourceParam = oauth.resource_url
    ? `\n    REFRESH_BODY="$REFRESH_BODY&resource=${encodeURIComponent(oauth.resource_url)}"`
    : "";

  return [
    "refresh_token_flow() {",
    "  local rt token_endpoint client_id",
    "  rt=$(jq -r '.refresh_token // empty' \"$TOKEN_FILE\")",
    "  token_endpoint=$(jq -r '.token_endpoint // empty' \"$TOKEN_FILE\")",
    "  client_id=$(jq -r '.client_id // empty' \"$TOKEN_FILE\")",
    "",
    "  if [ -z \"$rt\" ]; then",
    `    echo "Error: no refresh token — re-run: npx @filiksyos/mcptoskill ${oauth.mcp_url}" >&2`,
    "    exit 1",
    "  fi",
    "",
    "  REFRESH_BODY=\"grant_type=refresh_token&refresh_token=$rt&client_id=$client_id\"" +
      resourceParam,
    "",
    "  local resp",
    "  resp=$(curl -s -X POST \"$token_endpoint\" \\",
    "    -H \"Content-Type: application/x-www-form-urlencoded\" \\",
    "    -d \"$REFRESH_BODY\")",
    "",
    "  local new_at",
    "  new_at=$(echo \"$resp\" | jq -r '.access_token // empty')",
    "  if [ -z \"$new_at\" ]; then",
    `    echo "Error: token refresh failed — re-run: npx @filiksyos/mcptoskill ${oauth.mcp_url}" >&2`,
    "    echo \"$resp\" >&2",
    "    exit 1",
    "  fi",
    "",
    "  local new_rt new_exp now new_expires_at",
    "  new_rt=$(echo \"$resp\" | jq -r '.refresh_token // empty')",
    "  new_exp=$(echo \"$resp\" | jq -r '.expires_in // 3600')",
    "  now=$(date +%s)",
    "  new_expires_at=$((now + new_exp))",
    "",
    "  jq --arg at \"$new_at\" \\",
    "     --arg rt \"${new_rt:-$rt}\" \\",
    "     --argjson ea \"$new_expires_at\" \\",
    "     '.access_token=$at | .refresh_token=$rt | .expires_at=$ea' \\",
    "     \"$TOKEN_FILE\" > \"${TOKEN_FILE}.tmp\" && mv \"${TOKEN_FILE}.tmp\" \"$TOKEN_FILE\"",
    "  chmod 600 \"$TOKEN_FILE\"",
    "}",
  ];
}

function generateSupabaseRefreshFunction(oauth: OAuthTokenInfo): string[] {
  return [
    "refresh_token_flow() {",
    "  local rt token_endpoint client_id client_secret",
    "  rt=$(jq -r '.refresh_token // empty' \"$TOKEN_FILE\")",
    "  token_endpoint=$(jq -r '.token_endpoint // empty' \"$TOKEN_FILE\")",
    "  client_id=$(jq -r '.client_id // empty' \"$TOKEN_FILE\")",
    "  client_secret=$(jq -r '.client_secret // empty' \"$TOKEN_FILE\")",
    "",
    "  if [ -z \"$rt\" ]; then",
    `    echo "Error: no refresh token — re-run: npx @filiksyos/mcptoskill ${oauth.mcp_url}" >&2`,
    "    exit 1",
    "  fi",
    "",
    "  if [ -z \"$client_secret\" ]; then",
    `    echo "Error: token file missing client_secret — re-run: npx @filiksyos/mcptoskill ${oauth.mcp_url}" >&2`,
    "    exit 1",
    "  fi",
    "",
    "  local resp",
    "  resp=$(curl -s -X POST \"$token_endpoint\" \\",
    "    -H \"Content-Type: application/x-www-form-urlencoded\" \\",
    "    -u \"$client_id:$client_secret\" \\",
    "    -d \"grant_type=refresh_token&refresh_token=$rt\")",
    "",
    "  local new_at",
    "  new_at=$(echo \"$resp\" | jq -r '.access_token // empty')",
    "  if [ -z \"$new_at\" ]; then",
    `    echo "Error: token refresh failed — re-run: npx @filiksyos/mcptoskill ${oauth.mcp_url}" >&2`,
    "    echo \"$resp\" >&2",
    "    exit 1",
    "  fi",
    "",
    "  local new_rt new_exp now new_expires_at",
    "  new_rt=$(echo \"$resp\" | jq -r '.refresh_token // empty')",
    "  new_exp=$(echo \"$resp\" | jq -r '.expires_in // 3600')",
    "  now=$(date +%s)",
    "  new_expires_at=$((now + new_exp))",
    "",
    "  jq --arg at \"$new_at\" \\",
    "     --arg rt \"${new_rt:-$rt}\" \\",
    "     --argjson ea \"$new_expires_at\" \\",
    "     '.access_token=$at | .refresh_token=$rt | .expires_at=$ea' \\",
    "     \"$TOKEN_FILE\" > \"${TOKEN_FILE}.tmp\" && mv \"${TOKEN_FILE}.tmp\" \"$TOKEN_FILE\"",
    "  chmod 600 \"$TOKEN_FILE\"",
    "}",
  ];
}

function generateProxiedRefreshFunction(oauth: OAuthTokenInfo): string[] {
  return [
    "refresh_token_flow() {",
    "  local rt",
    "  rt=$(jq -r '.refresh_token // empty' \"$TOKEN_FILE\")",
    "",
    "  if [ -z \"$rt\" ]; then",
    `    echo "Error: no refresh token — re-run: npx @filiksyos/mcptoskill ${oauth.mcp_url}" >&2`,
    "    exit 1",
    "  fi",
    "",
    "  local resp",
    `  resp=$(curl -s -X POST "https://mcptoskill.com/api/refresh/${oauth.provider}" \\`,
    "    -H \"Content-Type: application/json\" \\",
    "    -d \"{\\\"refresh_token\\\":\\\"$rt\\\"}\") ",
    "",
    "  local new_at",
    "  new_at=$(echo \"$resp\" | jq -r '.access_token // empty')",
    "  if [ -z \"$new_at\" ]; then",
    `    echo "Error: token refresh failed — re-run: npx @filiksyos/mcptoskill ${oauth.mcp_url}" >&2`,
    "    echo \"$resp\" >&2",
    "    exit 1",
    "  fi",
    "",
    "  local new_rt new_exp now new_expires_at",
    "  new_rt=$(echo \"$resp\" | jq -r '.refresh_token // empty')",
    "  new_exp=$(echo \"$resp\" | jq -r '.expires_in // 3600')",
    "  now=$(date +%s)",
    "  new_expires_at=$((now + new_exp))",
    "",
    "  jq --arg at \"$new_at\" \\",
    "     --arg rt \"${new_rt:-$rt}\" \\",
    "     --argjson ea \"$new_expires_at\" \\",
    "     '.access_token=$at | .refresh_token=$rt | .expires_at=$ea' \\",
    "     \"$TOKEN_FILE\" > \"${TOKEN_FILE}.tmp\" && mv \"${TOKEN_FILE}.tmp\" \"$TOKEN_FILE\"",
    "  chmod 600 \"$TOKEN_FILE\"",
    "}",
  ];
}

export interface GeneratedSkill {
  skillName: string;
  skillMd: string;
  shellScript: string;
}

export function generate(
  result: McpClientResult,
  nameOverride?: string,
  oauth?: OAuthTokenInfo,
): GeneratedSkill {
  const skillName = nameOverride ?? slugify(result.serverInfo.name);
  return {
    skillName,
    skillMd: generateSkillMd(result, skillName),
    shellScript: oauth
      ? generateOAuthShellScript(result, skillName, oauth)
      : generateStaticShellScript(result, skillName),
  };
}
