import type { McpClientResult, Tool, ToolParam } from "./client.js";

function slugify(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}

function buildExampleArgs(params: ToolParam[]): string {
  const required = params.filter((p) => p.required);
  if (required.length === 0) return "'{}'";

  const example: Record<string, string> = {};
  for (const p of required) {
    example[p.name] = `<${p.name}>`;
  }
  return `'${JSON.stringify(example)}'`;
}

function generateSkillMd(result: McpClientResult, skillName: string): string {
  const { serverInfo, tools, serverUrl } = result;

  const triggerPhrases = tools
    .map((t) => t.name.replace(/-/g, " "))
    .join(", ");

  const toolDocs = tools
    .map((t) => {
      const paramLines = t.params.map((p) => {
        const req = p.required ? " (required)" : " (optional)";
        const desc = p.description ? `: ${p.description}` : "";
        return `  - \`${p.name}\` (${p.type})${req}${desc}`;
      });

      const exampleArgs = buildExampleArgs(t.params);

      return [
        `### ${t.name}`,
        "",
        t.description,
        "",
        ...(paramLines.length > 0 ? ["**Parameters:**", ...paramLines, ""] : []),
        "```bash",
        `{baseDir}/scripts/${skillName}.sh ${t.name} ${exampleArgs}`,
        "```",
      ].join("\n");
    })
    .join("\n\n");

  const metadataJson = JSON.stringify({ clawdbot: {} });

  return [
    "---",
    `name: ${skillName}`,
    `description: ${serverInfo.instructions ?? `Use ${serverInfo.name} tools.`} Triggers on: ${triggerPhrases}.`,
    `homepage: ${serverUrl}`,
    `metadata: ${metadataJson}`,
    "---",
    "",
    `# ${serverInfo.name}`,
    "",
    serverInfo.instructions ?? "",
    "",
    "## Quick Start",
    "",
    "```bash",
    `{baseDir}/scripts/${skillName}.sh <tool-name> '<json-args>'`,
    "```",
    "",
    "## Tools",
    "",
    toolDocs,
  ]
    .join("\n")
    .trim() + "\n";
}

function generateShellScript(result: McpClientResult, skillName: string): string {
  const { serverUrl } = result;

  const initBody = JSON.stringify({
    jsonrpc: "2.0",
    id: 0,
    method: "initialize",
    params: {
      protocolVersion: "2024-11-05",
      capabilities: {},
      clientInfo: { name: "mcptoskill", version: "0.1.0" },
    },
  });

  const lines = [
    "#!/bin/bash",
    `# Generated by mcptoskill — https://mcptoskill.com`,
    `# Server: ${result.serverInfo.name} v${result.serverInfo.version}`,
    `# URL: ${serverUrl}`,
    "set -euo pipefail",
    "",
    `TOOL_NAME="\${1:?Usage: ${skillName}.sh <tool-name> '<json-args>'}"`,
    `ARGS="\${2:-}"`,
    `[ -z "$ARGS" ] && ARGS='{}'`,
    `MCP_URL="${serverUrl}"`,
    "",
    "# Capture session ID from initialize (required for stateful servers; no-op for stateless)",
    "TEMP_HEADERS=$(mktemp)",
    "curl -s -X POST \"$MCP_URL\" \\",
    "  -H \"Content-Type: application/json\" \\",
    "  -H \"Accept: application/json, text/event-stream\" \\",
    "  -D \"$TEMP_HEADERS\" \\",
    `  -d '${initBody}' > /dev/null`,
    "",
    "SESSION_ID=$(grep -i \"^mcp-session-id:\" \"$TEMP_HEADERS\" | awk '{print $2}' | tr -d '\\r' || true)",
    "rm -f \"$TEMP_HEADERS\"",
    "",
    "# Call the tool",
    "if [ -n \"$SESSION_ID\" ]; then",
    "  curl -s -X POST \"$MCP_URL\" \\",
    "    -H \"Content-Type: application/json\" \\",
    "    -H \"Accept: application/json, text/event-stream\" \\",
    "    -H \"Mcp-Session-Id: $SESSION_ID\" \\",
    `    -d "{\\"jsonrpc\\":\\"2.0\\",\\"id\\":1,\\"method\\":\\"tools/call\\",\\"params\\":{\\"name\\":\\"$TOOL_NAME\\",\\"arguments\\":$ARGS}}"`,
    "else",
    "  curl -s -X POST \"$MCP_URL\" \\",
    "    -H \"Content-Type: application/json\" \\",
    "    -H \"Accept: application/json, text/event-stream\" \\",
    `    -d "{\\"jsonrpc\\":\\"2.0\\",\\"id\\":1,\\"method\\":\\"tools/call\\",\\"params\\":{\\"name\\":\\"$TOOL_NAME\\",\\"arguments\\":$ARGS}}"`,
    "fi",
    "",
  ];

  return lines.join("\n");
}

export interface GeneratedSkill {
  skillName: string;
  skillMd: string;
  shellScript: string;
}

export function generate(result: McpClientResult, nameOverride?: string): GeneratedSkill {
  const skillName = nameOverride ?? slugify(result.serverInfo.name);
  return {
    skillName,
    skillMd: generateSkillMd(result, skillName),
    shellScript: generateShellScript(result, skillName),
  };
}
